name: Docker Build

on:
  push:
    branches: [ "main" ]
    
jobs:
  # Build for multiple architectures
  build-multiarch:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKERREG_USERNAME }}
          password: ${{ secrets.DOCKERREG_TOKEN }}
          
      - name: Build and push AMD64
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          push: true
          tags: ${{ vars.DOCKER_REGISTRY }}vmo-frontend:dev
          
      - name: Build and push ARM64
        uses: docker/build-push-action@v6
        with:
          platforms: linux/arm64
          file: Dockerfile.arm64
          push: true
          tags: ${{ vars.DOCKER_REGISTRY }}vmo-frontend:arm64-dev
